-- 코드를 입력하세요
SELECT
P.PRODUCT_CODE,
SUM(P.PRICE * OS.SALES_AMOUNT) AS SALE
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALE DESC, P.PRODUCT_CODE