-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON P.CAR_TYPE = C.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
    WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'))
    AND C.CAR_TYPE IN ('SUV','세단')
    AND ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100,0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC