-- 코드를 작성해주세요
SELECT
ID, 
CASE 
    WHEN N / TOTAL <= 0.25 THEN 'CRITICAL'
    WHEN N / TOTAL <= 0.50 THEN 'HIGH'
    WHEN N / TOTAL <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, SIZE_OF_COLONY, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS N FROM ECOLI_DATA) AS E JOIN (SELECT COUNT(*) AS TOTAL FROM ECOLI_DATA AS E) AS D
ORDER BY E.ID 