-- 코드를 입력하세요
SELECT U.USER_ID, 
        U.NICKNAME,
        CONCAT(U.CITY, " ", U.STREET_ADDRESS1, " ", U.STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTRING(U.TLNO,1,3),'-',SUBSTRING(U.TLNO,4,4),'-',SUBSTRING(U.TLNO,8,4)) AS 전화번호
FROM (SELECT WRITER_ID, COUNT(WRITER_ID) AS CNT 
      FROM USED_GOODS_BOARD
      GROUP BY WRITER_ID
      HAVING COUNT(WRITER_ID) >= 3) AS B LEFT OUTER JOIN 
      USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC;
