SELECT 
    O.YEAR, 
    O.MONTH,
    U.GENDER,
    COUNT(O.USER_ID) AS USERS
FROM USER_INFO AS U JOIN (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
) AS O ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY O.YEAR, O.MONTH, U.GENDER
ORDER BY O.YEAR ASC, O.MONTH ASC, U.GENDER ASC
