-- 코드를 입력하세요
# SELECT COUNT(*) FROM ONLINE_SALE WHERE MONTH(SALES_DATE) = 1
# SELECT *
# FROM ONLINE_SALE AS O JOIN
#     (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021 ) AS U 
#     ON O.USER_ID = U.USER_ID

SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS O JOIN
    (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021 ) AS U 
    ON O.USER_ID = U.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)