-- 코드를 입력하세요
SELECT CAR_ID,
CASE 
    WHEN SUM(AVAIL) >= 1 THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY
FROM (SELECT
CAR_ID,
CASE 
    WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
    ELSE 0
END AS AVAIL
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS F
GROUP BY CAR_ID
ORDER BY CAR_ID DESC