-- 코드를 입력하세요
SELECT 
    HISTORY_ID, 
    ROUND(DAILY_FEE*IF(DISCOUNT_RATE, (100-DISCOUNT_RATE)/100,1)*DIFF,0) AS FEE
FROM (SELECT 
    H.HISTORY_ID, 
    DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DIFF,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE '-'
    END AS DURATION,
    C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H JOIN CAR_RENTAL_COMPANY_CAR AS C ON 
        H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭') AS HC LEFT OUTER JOIN 
        (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭')
        AS P ON HC.DURATION = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
