-- 코드를 작성해주세요
SELECT R.ITEM_ID, R.ITEM_NAME, R.RARITY
FROM ITEM_INFO AS P
    JOIN ITEM_TREE AS T ON P.ITEM_ID = T.PARENT_ITEM_ID
    JOIN ITEM_INFO AS R ON T.ITEM_ID = R.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY R.ITEM_ID DESC;