-- 코드를 작성해주세요
SELECT 
    HG.SS AS SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES AS HE JOIN 
    (SELECT EMP_NO, SUM(SCORE) AS SS FROM HR_GRADE GROUP BY EMP_NO ) AS HG
    ON HE.EMP_NO = HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;