-- 코드를 입력하세요

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN 
    (SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES 
     WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01' GROUP BY BOOK_ID)
    AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY