-- 코드를 입력하세요
SELECT C.CATEGORY,C.MAX_PRICE, F.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
    FROM FOOD_PRODUCT 
    GROUP BY CATEGORY) AS C RIGHT OUTER JOIN FOOD_PRODUCT AS F ON C.CATEGORY = F.CATEGORY
WHERE F.CATEGORY IN ('과자','국','김치','식용유') AND C.MAX_PRICE = F.PRICE
ORDER BY MAX_PRICE DESC