-- 코드를 작성해주세요
SELECT 
    CASE 
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 
            CASE 
                WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') > 0 THEN 'A'
                WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') >0 THEN 'B'
                ELSE 'C'
        END
        ELSE 'B'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS 
WHERE SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') != 0 OR
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0
ORDER BY GRADE ASC, ID ASC